version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elasticsearch7.6.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    hostname: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana7.6.1
    environment:
      - I18N_LOCALE=zh-CN
      - elasticsearch.hosts=http://elasticsearch:9200
    hostname: kibana
    depends_on:
      - elasticsearch
    restart: always
    ports:
      - "5601:5601"
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.1
    container_name: logstash7.6.1
    hostname: logstash
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/conf.d/:/usr/share/logstash/conf.d/  
    ports:
      - 9600:9600
      - 5044:5044
  cerebro:
      image: lmenezes/cerebro:0.8.3
      container_name: cerebro
      restart: always
      ports:
        - "9000:9000"
      command:
        - -Dhosts.0.host=http://localhost:9200
  elastichd:
    image: containerize/elastichd:latest
    container_name: elasticsearch-hd
    restart: always
    ports:
      - "9800:9800"
    depends_on:
      - "elasticsearch"
    links:
      - "elasticsearch:demo"
volumes:
  esdata:
    driver: local
